---
extends:
  - wotan:latest
  - "@fimbul/disir"
rules:
  type-assertion:
    options:
      style: classic
overrides:
  - files: "packages/*/test/**"
    rules:
      no-unstable-api-use: off
      no-inferred-empty-object: off
  - files: "packages/**"
    rules:
      disir/import-package: error
      disir/no-barrel-import: error
      disir/no-import-self: error
