---
extends:
  - wotan:latest
  - "@fimbul/disir"
rules:
  no-useless-predicate: off # TODO enable ASAP
  no-useless-assertion: off # TODO enable ASAP
  type-assertion:
    options:
      style: classic
  parameter-properties:
    options:
      mode: when-possible
  no-implicit-tostring:
    options:
      allowNumber: true
      allowNever: true
overrides:
  - files: "packages/*/test/**"
    rules:
      no-unstable-api-use: off
      no-uninferred-type-parameter: off
  - files: "packages/**"
    rules:
      disir/import-package: error
      disir/no-barrel-import: error
      disir/no-import-self: error
