# Test against the latest version of Node.js
environment:
  nodejs_version: ""

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build: off

test_script:
  - yarn compile
  - yarn lint
  - yarn coverage test:api
  - yarn report-coverage -F unit
  - yarn coverage test:integration
  - yarn report-coverage -F integration
  - yarn coverage test:rules
  - yarn report-coverage -F rules
