# Test against the latest version of Node.js
environment:
  nodejs_version: ""

cache:
  - node_modules
  - "packages\\*\\node_modules"
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build: off

test_script:
  - yarn compile
  - yarn lint
  - yarn coverage yarn test
  - yarn report-coverage
