# Test against the latest version of Node.js
environment:
  nodejs_version: ""

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build: off

test_script:
  - yarn compile
  - yarn lint
  - yarn coverage node_modules/.bin/run-p test:integration "test:unit -s -c 2"
  - yarn report-coverage
