# Test against the latest version of Node.js
environment:
  nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

build: off

test_script:
  - yarn compile --incremental false
  - yarn lint
  - node_modules/.bin/nyc --cache=false node_modules/.bin/run-p test:integration test:unit
  - yarn report-coverage
