rulesDirectories:
  '@typescript-eslint': './node_modules/@typescript-eslint/eslint-plugin/dist/rules'
rules:
  no-console: warn
  '@typescript-eslint/await-thenable': error
  '@typescript-eslint/no-floating-promises': error
  '@typescript-eslint/no-misused-promises': error
