workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.2:
          requires:
            - build
      - test@3.3:
          requires:
            - build
      - test@3.4:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn coverage yarn test
          yarn report-coverage

version: 2
jobs:
  build:
    working_directory: '~/Project'
    docker:
      - image: circleci/node:10@sha256:0773345d355370ae5a00545309c6b5d2758807037a8bb72de0b33a0d39b11904
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:11@sha256:606b7dc62ae65958a00328dd900dee1589681464fb532c3a46f6bc3fe44e9882
    <<: *base
  test@3.2:
    docker:
      - image: circleci/node:6@sha256:6b5eed4f363e33e7acb12ba315dc9737c92f2665d0abe21d00fb9cbdbc6314b9
    environment:
      typescriptVersion: "3.2"
    <<: *base
  test@3.3:
    docker:
      - image: circleci/node:8@sha256:fc51ca28d5731a23bbc2d08d8c8891fc50a2858e87db9646b8eca154bf6a83d5
    environment:
      typescriptVersion: "3.3"
    <<: *base
  test@3.4:
    docker:
      - image: circleci/node:10@sha256:0773345d355370ae5a00545309c6b5d2758807037a8bb72de0b33a0d39b11904
    environment:
      typescriptVersion: "3.4"
    <<: *base
