workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.3:
          requires:
            - build
      - test@3.4:
          requires:
            - build
      - test@3.5:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn test-coverage
          yarn report-coverage

version: 2
jobs:
  build:
    working_directory: '~/Project'
    docker:
      - image: circleci/node:12@sha256:3ce87c0ad400007a6bfe38cb0f61777800ea20ee30304982df998e8ae7b0eba6
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:12@sha256:3ce87c0ad400007a6bfe38cb0f61777800ea20ee30304982df998e8ae7b0eba6
    <<: *base
  test@3.3:
    docker:
      - image: circleci/node:8@sha256:47a870fd1e15231e0b63a40ca45e2d43e01006ccc4b723f3ddd2a1196a15804d
    environment:
      typescriptVersion: "3.3"
    <<: *base
  test@3.4:
    docker:
      - image: circleci/node:10@sha256:78c8f87e261daca98d6a45acd76a3d88e14ef709cc5ac93b723f204143f610c0
    environment:
      typescriptVersion: "3.4"
    <<: *base
  test@3.5:
    docker:
      - image: circleci/node:12@sha256:3ce87c0ad400007a6bfe38cb0f61777800ea20ee30304982df998e8ae7b0eba6
    environment:
      typescriptVersion: "3.5"
    <<: *base
