workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@2.4:
          requires:
            - build
      - test@2.6:
          requires:
            - build
      - test@next:
          requires:
            - build

base: &base
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -W typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn coverage yarn test
          yarn report-coverage

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10@sha256:a9922d47c3f9efeebcd65d11610c4f23e1a38ee92624f4058ed8f6eb65f1789f
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:9@sha256:1436452688e55a3662983871f1657c222f4a2405582de685570809fd584ea1e5
    <<: *base
  test@2.4:
    docker:
      - image: circleci/node:6@sha256:dc5d7b4659bf5b1a56b5c07e4ea7d8a68acf90403fe6bb3bf617e548cd233944
    environment:
      typescriptVersion: 2.4
    <<: *base
  test@2.6:
    docker:
      - image: circleci/node:8@sha256:fdad4eb2cc225a5c1b56fc6ac1fe275f5f92434f135f63fbc95894274753adc3
    environment:
      typescriptVersion: 2.6
    <<: *base
  test@next:
    docker:
      - image: circleci/node:10@sha256:a9922d47c3f9efeebcd65d11610c4f23e1a38ee92624f4058ed8f6eb65f1789f
    environment:
      typescriptVersion: next
    <<: *base
