workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.2:
          requires:
            - build
      - test@3.3:
          requires:
            - build
      - test@3.4:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn coverage yarn test
          yarn report-coverage

version: 2
jobs:
  build:
    working_directory: '~/Project'
    docker:
      - image: circleci/node:10@sha256:09d5e11f359d588c1a50d299db281f7c1a3ee54a1ad15728a3180bbe3a95242e
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:11@sha256:0a7f3ad3bc1bc37a629df50e94780228b3d810add75eaa89ee94e7fc26a28ce4
    <<: *base
  test@3.2:
    docker:
      - image: circleci/node:6@sha256:ef24608cee4e4b75f25b260a4f4e099b175c7c975ba5d7c13856512c9073edff
    environment:
      typescriptVersion: "3.2"
    <<: *base
  test@3.3:
    docker:
      - image: circleci/node:8@sha256:ef1a0c468510c5f3de8fe9dbccb7dfaf29d7e21086e7db2bb59cdc811b30ae80
    environment:
      typescriptVersion: "3.3"
    <<: *base
  test@3.4:
    docker:
      - image: circleci/node:10@sha256:09d5e11f359d588c1a50d299db281f7c1a3ee54a1ad15728a3180bbe3a95242e
    environment:
      typescriptVersion: "3.4"
    <<: *base
