workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.3:
          requires:
            - build
      - test@3.4:
          requires:
            - build
      - test@3.5:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn test-coverage
          yarn report-coverage

version: 2
jobs:
  build:
    working_directory: '~/Project'
    docker:
      - image: circleci/node:12@sha256:27dadd5b63738b43962c5c7486ac74792fe76ddd555d61d5b18c29f0f257e421
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:12@sha256:27dadd5b63738b43962c5c7486ac74792fe76ddd555d61d5b18c29f0f257e421
    <<: *base
  test@3.3:
    docker:
      - image: circleci/node:8@sha256:1fad5860c7b4a0057aae4fb9c0d273c6d7452c0c24a33931941358b546f3e424
    environment:
      typescriptVersion: "3.3"
    <<: *base
  test@3.4:
    docker:
      - image: circleci/node:10@sha256:6ab62742cec4a68e75e7cac063f6549bae0bcfd0541700df7fde54765eed4ad2
    environment:
      typescriptVersion: "3.4"
    <<: *base
  test@3.5:
    docker:
      - image: circleci/node:12@sha256:27dadd5b63738b43962c5c7486ac74792fe76ddd555d61d5b18c29f0f257e421
    environment:
      typescriptVersion: "3.5"
    <<: *base
