workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.5:
          requires:
            - build
      - test@3.6:
          requires:
            - build
      - test@3.7:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          node_modules/.bin/nyc node_modules/.bin/run-s test
          yarn report-coverage

latestNodeImage: &latestNodeImage
  docker:
    - image: circleci/node:13@sha256:ec3911f65acd2c1627e238d94acd436c5ee4cdc2bcf66e5ba3127bf998e25e8e

version: 2
jobs:
  build:
    working_directory: '~/Project'
    <<: *latestNodeImage
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    <<: *latestNodeImage
    <<: *base
  test@3.5:
    docker:
      - image: circleci/node:10@sha256:49eaf9ad1c4357e3a91ff778d80f84c14f4fcd4d5b71410b169227e07ed00702
    environment:
      typescriptVersion: "3.5"
    <<: *base
  test@3.6:
    docker:
      - image: circleci/node:12@sha256:697ce80faee28b4e56fb3db4e8d8061fab1414868061e620ecaf388065b7027f
    environment:
      typescriptVersion: "3.6"
    <<: *base
  test@3.7:
    <<: *latestNodeImage
    environment:
      typescriptVersion: "3.7"
    <<: *base
