workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.9:
          requires:
            - build
      - test@4.0:
          requires:
            - build
      - test@4.1:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          node_modules/.bin/nyc node_modules/.bin/run-s test
          yarn report-coverage

latestNodeImage: &latestNodeImage
  docker:
    - image: circleci/node:15

version: 2
jobs:
  build:
    working_directory: '~/Project'
    <<: *latestNodeImage
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    <<: *latestNodeImage
    <<: *base
  test@3.9:
    docker:
      - image: circleci/node:10@sha256:8f22fbc5189c13b42a7bdd3c775ccb272834dedc2401ecb988d2e827d5201d4c
    environment:
      typescriptVersion: "3.9"
    <<: *base
  test@4.0:
    docker:
      - image: circleci/node:12@sha256:e20c1e0e164313ce8c713281cd3b1f206aac0467fc6590972633f391e3231db6
    environment:
      typescriptVersion: "4.0"
    <<: *base
  test@4.1:
    docker:
      - image: circleci/node:14
    environment:
      typescriptVersion: "4.1"
    <<: *base
