workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.1:
          requires:
            - build
      - test@3.2:
          requires:
            - build
      - test@3.3:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -DW typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn coverage yarn test
          yarn report-coverage

version: 2
jobs:
  build:
    working_directory: '~/Project'
    docker:
      - image: circleci/node:10@sha256:9e8c9bb16cf9444e765e2a740313bb71bb8f9f647064eb4ecf45cfc39408179c
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:11@sha256:81881f0f6563580d288b075e1e4d0ef71907ef85f9d8cfaaa4e9428bf7e28b0f
    <<: *base
  test@3.1:
    docker:
      - image: circleci/node:6@sha256:07905fc81f50ff45dc01b82cae9bf4d38b8cb83a4fd2ab459ee4a920dc8cd54c
    environment:
      typescriptVersion: "3.1"
    <<: *base
  test@3.2:
    docker:
      - image: circleci/node:8@sha256:b503e29b2d3afc23ad3344fef640e5356f26dbed0474031f4598e90126af26ed
    environment:
      typescriptVersion: "3.2"
    <<: *base
  test@3.3:
    docker:
      - image: circleci/node:10@sha256:9e8c9bb16cf9444e765e2a740313bb71bb8f9f647064eb4ecf45cfc39408179c
    environment:
      typescriptVersion: "3.3"
    <<: *base
