workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@3.9:
          requires:
            - build
      - test@4.0:
          requires:
            - build
      - test@4.1:
          requires:
            - build

base: &base
  working_directory: '~/Project' # to really test case sensitivity
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          if [[ "$CIRCLE_JOB" =~ ^test@ ]]; then
            yarn add -DW typescript@${CIRCLE_JOB#test@}
          else
            yarn
          fi
    - run:
        name: Run Tests
        command: |
          node_modules/.bin/nyc node_modules/.bin/run-s test
          yarn report-coverage

latestNodeImage: &latestNodeImage
  docker:
    - image: circleci/node:15@sha256:64300d4fa16456a547e9e747a10e5eb02419a477ac08a592244dc5ca8adbda72

version: 2
jobs:
  build:
    working_directory: '~/Project'
    <<: *latestNodeImage
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Public API guard
          command: yarn check-package
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/wotan/language-service"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    <<: *latestNodeImage
    <<: *base
  test@3.9:
    docker:
      - image: circleci/node:10@sha256:b29187103f1ee3f1df2a3b61bbb1230333cddbd241a6dfc1d39c4ac0fbe1ba35
    <<: *base
  test@4.0:
    docker:
      - image: circleci/node:12@sha256:27ff7183ab5e2fe5138ad4ac3ddada57f0adbc72668f462faf6be3f1926f0ab0
    <<: *base
  test@4.1:
    docker:
      - image: circleci/node:14@sha256:b094e85848b43209ca83d9bb114d406fe62c75cb73b18c9d8eb1a9c6462c97d4
    <<: *base
