workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - test@2.8:
          requires:
            - build
      - test@2.9:
          requires:
            - build
      - test@3.0:
          requires:
            - build

base: &base
  steps:
    - checkout
    - attach_workspace:
        at: '.'
    - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
    - run:
        name: Install correct TypeScript version
        command: |
          yarn ${typescriptVersion:+add -W typescript@$typescriptVersion}
    - run:
        name: Run Tests
        command: |
          yarn coverage yarn test
          yarn report-coverage

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10@sha256:37a9958a87a806664578bca2cc721ab1886aee95efc3771ddb9051bdd33960f3
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Dependency check
          command: yarn check-dependencies
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: '.'
          paths:
            - "packages/*/index.*"
            - "packages/*/src"
            - "packages/*/test"
            - yarn.lock
  test:
    docker:
      - image: circleci/node:10@sha256:37a9958a87a806664578bca2cc721ab1886aee95efc3771ddb9051bdd33960f3
    <<: *base
  test@2.8:
    docker:
      - image: circleci/node:8@sha256:4442857368f68ed5e6e2841abbcec6bd610084d5e97bbc5e9e7b65edac0bcf53
    environment:
      typescriptVersion: 2.8
    <<: *base
  test@2.9:
    docker:
      - image: circleci/node:10@sha256:37a9958a87a806664578bca2cc721ab1886aee95efc3771ddb9051bdd33960f3
    environment:
      typescriptVersion: 2.9
    <<: *base
  test@3.0:
    docker:
      - image: circleci/node:10@sha256:37a9958a87a806664578bca2cc721ab1886aee95efc3771ddb9051bdd33960f3
    environment:
      typescriptVersion: 3.0
    <<: *base
