---
rules:
  await-promise: error
  deprecation: error
  generator-yield: error
  no-debugger: error
  no-fallthrough: error
  no-inferred-empty-object: error
  no-return-await: error
  no-unsafe-finally: error
  no-unused-expression: error
  no-unused-label: error
  no-useless-assertion: error
  no-useless-initializer: error
  trailing-newline: error
  try-catch-return-await: error
  use-isnan: error
