---
rules:
  await-async-result: error
  await-only-promise: error
  generator-yield: error
  no-debugger: error
  no-fallthrough: error
  no-inferred-empty-object: error
  no-return-await: error
  no-nan-compare: error
  no-unsafe-finally: error
  no-unstable-api-use: error
  no-unused-expression: error
  no-unused-label: error
  no-useless-assertion: error
  no-useless-initializer: error
  prefer-number-isnan: error
  prefer-object-spread: error
  trailing-newline: error
  try-catch-return-await: error
